### PR TITLE
Fix invalid prefix in add command

### LINKED ISSUE #238: [PE-D][Tester C] Unknown prefix in add command produces misleading phone number error
Type: Usability  
Severity: Medium  
Where found: JAR  

Steps to reproduce:
1. Launch the application.
2. Enter the command:
   add n/John p/1234567 x/hello

Expected:
The application should report that x/ is an invalid or unsupported prefix for the add command.

Actual:
The application displays a phone-number validation error:
"Phone number must be 7 to 15 digits and contain only numbers..."

Why this is an issue:
The input contains an unsupported prefix (x/), but the application reports a phone number validation error instead. This may mislead users into correcting the wrong field, making it harder to identify the actual issue.

Suggested fix:
Detect unsupported prefixes explicitly and display an error message indicating the invalid prefix.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by Nathan0820**

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -28,6 +40,36 @@ public class ParserUtil {
...
+     * Ensures {@code value} does not contain a substring that looks like an unknown field prefix (e.g. {@code x/hello})
+     * that is not one of the allowed {@link Prefix}
+     *
+     * @return {@code value} unchanged, for convenient chaining into {@code parseX} methods
+     */
+    public static String ensureNoUnsupportedPrefixTokensInValue(String value, Prefix... allowedPrefixes)
+            throws ParseException {
+        requireNonNull(value);
+        requireNonNull(allowedPrefixes);
+        Set<String> allowed = Arrays.stream(allowedPrefixes).map(Prefix::getPrefix).collect(Collectors.toSet());
```
Comment (gracias022) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:62]: actualled since u alr have the allowedPrefixes, would it be better to show the error message as "Unsupported prefix .... Valid prefixes: ..."

e.g. 
> Unsupported prefix 'x/' in this command. Valid prefixes: n/, p/, fb/, ig/, a/, r/, t/.

**Comment by gracias022** [comment]
wait @Nathan0820 i think there's an issue now, previously we accepted / in names, e.g. Ravi S/O Ramasamy, now thats rejected even though its a valid name

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 1 above)
Comment (Nathan0820) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java:62]: sure!

**Comment by Nathan0820** [comment]
> wait @Nathan0820 i think there's an issue now, previously we accepted / in names, e.g. Ravi S/O Ramasamy, now thats rejected even though its a valid name

I think we have 2 options now:
1. We ban names with `/` in ug
2. I try to see if i can implement escape characters to allow names with `/`

Which you think works best?

**Comment by gracias022** [comment]
> > wait @Nathan0820 i think there's an issue now, previously we accepted / in names, e.g. Ravi S/O Ramasamy, now thats rejected even though its a valid name
> 
> I think we have 2 options now:
> 
> 1. We ban names with `/` in ug
> 2. I try to see if i can implement escape characters to allow names with `/`
> 
> Which you think works best?

i think 2 wld be better, as i feel it's allowing / in names is sth alot of testers will nitpick on

**Comment by Nathan0820** [comment]
okok

File: src/main/java/seedu/address/model/person/Name.java [hunk 2]
```diff
@@ -15,6 +15,7 @@ public class Name {
         • be 1 to %d characters long
         • start with an alphanumeric character
         • contain only letters, numbers, spaces, apostrophes ('), slashes (/), and hyphens (-)
+        • use \\/ in the command if you need a literal / and it would otherwise be parsed incorrectly
```
Comment (gracias022) [inline src/main/java/seedu/address/model/person/Name.java]: wld replacing 'and' with 'as' be better?

**Comment by gracias022** [comment]
ive tested it and it works! saw the update in the UG, thankss

File: docs/UserGuide.md [hunk 3]
```diff
@@ -144,6 +144,7 @@ Adds a customer to the customer database.
 Format: `add n/NAME [p/PHONE] [ig/INSTAGRAM] [fb/FACEBOOK] [a/ADDRESS] [r/REMARK] [t/TAG]…​`
 
 * `NAME` is mandatory. It must be 1 to 100 characters long, start with an alphanumeric character, and contain only letters, numbers, spaces, apostrophes (`'`), slashes (`/`), and hyphens (`-`).
+  * If you need a `/` in the name, type **`\/`** for a literal slash. BZNUS stores the name with a normal `/` (the backslash is not kept). Example: `n/Ravi S\/O Ramasamy` is stored as `Ravi S/O Ramasamy`.
```
Comment (gracias022) [inline docs/UserGuide.md]: nice clarification

**Review by gracias022 — APPROVED** [review]

**Comment by gracias022** [comment]
i think there might be a limitation for this:
since currently only name, phone, ig, fb fields are checked, this means invalid prefixes appearing right after r/ , a/ or t/ are not detected 

e.g. `add n/hi r/eating chicken/fish today x/o d/p p/12043197` : no error
`add n/Tan t/eating a/13134095 street later/tonight l/0 p/12091431` : no error

`edit 1 t/vip o/hello` gives the error: Tag must contain at least one letter or number, and may include spaces, underscores, and hyphens.

i think it's expected for r/ and a/ given that they both allow /, might be good to document this limitation

but since tags disallow /, might it be better to also check for invalid prefixes after tags?

**Review by chenzmxy — APPROVED** [review]

**Review by tc363 — APPROVED** [review]
