### PR TITLE
Fix functional bugs for find-o and customer address

### LINKED ISSUE #198: [PE-D][Tester D] Filtering customer list via 'find' causes orders to show 'Unknown Customer' instead of actual customer name
### Steps to reproduce
1. Use the `find` command to filter
2. Return command and observe error message

### Expected result
Each order should display the actual customer name it belongs to, resolved from the full customer database regardless of the current filter state.

### Actual result
Observe the `Customer: Unknown` portion for orders that don't belong to Bernice Yu
Image

### Additional findings
Even after running `list` and `list-o` commands, which should display the complete, unfiltered dataset, orders that previously showed `Customer: Unknown` still display `Customer: Unknown`.
Image

-------------
Labels: `severity.High` `type.FunctionalityBug`

### LINKED ISSUE #199: [PE-D][Tester E] Order customer becomes unknown when doing find command followed by order
I don't know whether this is something only I am experiencing but doing this specific order of commands will cause customer in order tabs to become unknown. Like the app just forgot who the customers are, I think its just a UI bug as typing list-o after will fix it. It's not a very intrusive bug its just something the user will notice and find it weird!

Here are the steps to recreate it:
1. Using the default BZNUS on launch, type cmd `find alex`

Image

Image

2. Then add order using cmd `order 1 i/Chicken Cutlet q/2 at/2026-02-02 1900`

Image

It's probably a UI bug. It's a small issue and does not interfere with the functionality of the app so I gave it severity: Medium

PS I actually don't know how to reproduce the fix cause I just spam list/list-o and clicked Bernice Yu then it came back :)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #200: [PE-D][Tester E] Order customer becomes unknown when doing find command followed by delete
It's the same as before but this time after find Alex if you delete something it will cause the customers to be shown as unknown. I think it's just cause only orders for Alex are loaded? The orders with Alex have the correct customer fields.

Starting from the state after adding an order from the previous bug (the find then add order one)

Image

Resetting back to the state where you can see all the customer names

Image

Image

Looking at my order#11. if I type `delete-o 11`:

Image

Everyone's orders that are not Alex Yeoh one are set to unknown!

Anyways I think the cause is probably the same as the previous one so the severity is the same .(I gotta report bugs I'm sorry) 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #203: [PE-D][Tester E] Remarks and Address allows for non-alphanumeric characters
Not sure if this is intended design but users are allowed to input in characters like Chinese characters into the app under the remarks/address tab.

Image

It might just be a small nitpick but since names are locked to be alphanumeric should the other fields (particularly address) be also locked to alphanumeric + symbols so that the fields are more consistent? It's a small nitpick though and final decision is up to y'all, I just think the app will look nicer and more consistent if there are no like characters from other languages in the fields since all the names are fixed to alphanumeric! 

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #224: [PE-D][Tester E] find command followed by list-o gives Unknown Customers in order
I think the orders is not updating it keeps showing unknown customers for customers not displayed under customer list after find.
After finding a bunch of customers, if you click on one of the customers then type `list-o`, the customer orders for those not displayed on the left lift will become Customer: Unknown.

Reproduce steps: I have 2 Bernice and 3 Orders. Each Bernice has 1 order each and David Li has the 3rd order.

1. `find Bernice`

Image

2. Click on the first Bernice (Bernice Tan in my case) to reload the order list

Image

3. Now type command `list-o`

Image

Apparently if I type `list` to list the full customer list then click a few times anywhere on the app it will refresh and change the unknown to the correct customer. (I click mostly at the order list there in the UI)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by chenzmxy**

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Address.java [hunk 1]
```diff
@@ -11,13 +12,16 @@ public class Address {
...
     /*
-     * The first character of the address must not be a whitespace,
-     * otherwise " " (a blank string) becomes a valid input.
+     * Address format: Street Address, City, Postal Code
+     * Each section separated by comma.
+     * Allows: alphanumeric, spaces, and symbols (. , ' - / # &)
+     * This enforces a structured address format with three components.
      */
-    public static final String VALIDATION_REGEX = "[^\\s].{0,199}";
+    public static final String VALIDATION_REGEX = "^[a-zA-Z0-9][a-zA-Z0-9,.\\s'\\-/#&]*,[\\s]*[a-zA-Z0-9][a-zA-Z0-9\\s'\\-]*,[\\s]*[a-zA-Z0-9]{0,199}$";
```
Comment (gracias022) [inline src/main/java/seedu/address/model/person/Address.java]: @chenzmxy i think your version might be too strict
Enforcing 'Street Address, City, Postal Code' might reduce usability for users who wld want to record addresses fast

typically they might omit city too (e.g. in sg), or some might wish to record without commas
e.g. 

- `#02-01 Blk 123`
- ` 1 Fusionopolis Way, B1 #01-01`
- ` Blk 441 Clementi Ave 3`

would this be better 
> ^[a-zA-Z0-9#][A-Za-z0-9 ,.'/#&()\-]{0,199}$

File: src/main/java/seedu/address/model/person/Address.java [hunk 2]
```diff
@@ -11,13 +11,17 @@ public class Address {
 
     public static final int MAX_ADDRESS_LENGTH = 200;
     public static final String MESSAGE_CONSTRAINTS =
-            "Address can take any value, must not be blank, and must not exceed " + MAX_ADDRESS_LENGTH + " characters.";
+            "Address must only contain alphanumeric characters, spaces and "
+            + "the following special characters: ,.'/#&()-.\n"
+            + "Each section must start with alphanumeric characters, and must not exceed "
```
Comment (tc363) [inline src/main/java/seedu/address/model/person/Address.java]: for 'each section must start with...', do u mean the entire address must start with alphanumeric?

**Comment by tc363** [comment]
tested, unknown customer no longer appears

File: src/main/java/seedu/address/model/person/Address.java (hunk 2 above)
Comment (gracias022) [reply src/main/java/seedu/address/model/person/Address.java]: @chenzmxy  i think it should be 

> It must start with an alphanumeric character, and must not exceed ...

instead of 
>Each section must start with alphanumeric characters, and must not exceed ...

**Review by tc363 — APPROVED** [review]

**Review by gracias022 — APPROVED** [review]
